# Generated by Django 3.2.6 on 2021-08-17 19:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music_nation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30)),
                ('uploaded_on', models.DateField(default=datetime.datetime(2021, 8, 17, 19, 40, 55, 768688))),
                ('album_logo', models.FileField(upload_to=music_nation.models.user_directory_path)),
                ('album_genre', models.CharField(max_length=30)),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=40)),
                ('song_file', models.FileField(upload_to=music_nation.models.user_directory_path_song)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_nation.album')),
            ],
        ),
    ]
